#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

gputhreshold_predef="0"
gputhreshold_find=`grep "gputhreshold_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value gpu_control_threshold $gpu_control_threshold
  edit_value gputhreshold_predef $gputhreshold_predef 

  echo $gpu_control_threshold > /sys/class/misc/gpu_control/gpu_clock_control
}

case "$gputhresholdpredef" in
  0)
    # ExtraBattsave (Máximo Ahorro de Batería)
    # Threshold0-1/up-down: 70% 62%
    # Threshold1-2/up-down: 90% 85%
    # Threshold2-3/up-down: 90% 85%
    # Threshold3-4/up-down: 90% 85%
    gpu_control_threshold="70% 62% 90% 85% 90% 85% 90% 85%"
    gputhreshold_predef="0"
    write_values
    ;;
  1)
    # Moderado (Javilonas)
    # Threshold0-1/up-down: 62% 54%
    # Threshold1-2/up-down: 82% 77%
    # Threshold2-3/up-down: 82% 77%
    # Threshold3-4/up-down: 82% 77%
    gpu_control_threshold="62% 54% 82% 77% 82% 77% 82% 77%"
    gputhreshold_predef="1"
    write_values
    ;;
  2)
    # Battsave (Ahorrar Batería)
    # Threshold0-1/up-down: 50% 42%
    # Threshold1-2/up-down: 70% 65%
    # Threshold2-3/up-down: 70% 65%
    # Threshold3-4/up-down: 70% 65%
    gpu_control_threshold="50% 42% 70% 65% 70% 65% 70% 65%"
    gputhreshold_predef="2"
    write_values
    ;;
  3)
    # Normal (STOCK)
    # Threshold0-1/up-down: 40% 32%
    # Threshold1-2/up-down: 60% 55%
    # Threshold2-3/up-down: 60% 55%
    # Threshold3-4/up-down: 60% 55%
    gpu_control_threshold="40% 32% 60% 55% 60% 55% 60% 55%"
    gputhreshold_predef="3"
    write_values
    ;;
  4)
    # Semi-Performance (Javilonas) (Para Jugones no exigentes)
    # Threshold0-1/up-down: 35% 27%
    # Threshold1-2/up-down: 55% 50%
    # Threshold2-3/up-down: 55% 50%
    # Threshold3-4/up-down: 55% 50%
    gpu_control_threshold="35% 27% 55% 50% 55% 50% 55% 50%"
    gputhreshold_predef="4"
    write_values
    ;;
  5)
    # Performance (Expecial Gamers insatisfechos)
    # Threshold0-1/up-down: 30% 22%
    # Threshold1-2/up-down: 50% 45%
    # Threshold2-3/up-down: 50% 45%
    # Threshold3-4/up-down: 50% 45%
    gpu_control_threshold="30% 22% 50% 45% 50% 45% 50% 45%"
    gputhreshold_predef="5"
    write_values
    ;;
  *)
    if [[ ! -z $gputhreshold_find ]]; then
      gputhreshold_predef="$gputhreshold_find"
    fi 
    ;;
esac;

eval echo $gputhreshold_predef
