#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

enable_mask_predef="0"
enable_mask_find=`grep "enable_mask_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value enable_mask $enable_mask
  edit_value enable_mask_predef $enable_mask_predef 

  echo $enable_mask > /sys/module/cpuidle_exynos4/parameters/enable_mask
}

case "$enable_maskpredef" in
  0)
    # Idle
    enable_mask="0"
    enable_mask_predef="0"
    write_values
    ;;
  1)
    # AFTR
    enable_mask="1"
    enable_mask_predef="1"
    write_values
    ;;
  2)
    # Idle + LPA
    enable_mask="2"
    enable_mask_predef="2"
    write_values
    ;;
  3)
    # AFTR + LPA
    enable_mask="3"
    enable_mask_predef="3"
    write_values
    ;;
  *)
    if [[ ! -z $enable_mask_find ]]; then
      enable_mask_predef="$enable_mask_find"
    fi 
    ;;
esac;

eval echo $enable_mask_predef
